### ISSUE TITLE
Tarball release contains prebuilt documentation.

### ISSUE THREAD

**Issue by frediz** [sphde/sphde#12]
Hi,
as a source tarball, is it supposed to provide prebuilt html ?
Debian/Ubuntu packaging is not expecting that, nor having javascript embedded (which don't come from this project).
I can workaround that html prebuilt files and add licensing information about .js coming 
from other projects, but I'm just asking if it doesn't harm to remove that or if there is a 
specific reason to have non-source files in a source tarball.
Thanks,
Fred

**Comment by RajalakshmiS** [comment]
Looking at the changlog , I could see commit https://github.com/sphde/sphde/commit/a72713d51a823511a34a18dd61d542faada6ce99
started to build html files, though html files  are tracked and hosted at
https://github.com/sphde/sphde.github.io  and http://sphde.github.io/

@frediz , Any specific reason why you have added that?

**Comment by frediz** [comment]
Hi,
my bad :) , it seems the make dist is now generating a dist tarball with a generated html inside doc/ directory. I'll check how I can fix that.
The patch was not intended to generate a dist package with doc, only to make available the generation of the documentation with the Makefile : I needed the manpage that was not generated before that.
I didn't check target "dist".
As for html files, they are on https://github.com/sphde/sphde.github.io to serve http://sphde.github.io/ but the sources are in this repo.
Thanks for pointing out my mistake,
F.

**Comment by RajalakshmiS** [comment]
@frediz , Can I close this?

**Comment by frediz** [comment]
@RajalakshmiS yes.
Thank you
