### ISSUE TITLE
Shared lib calling exit

### ISSUE THREAD

**Issue by frediz** [sphde/sphde#13]
Hi,
while running lintian on debian to check the packaging, it complains about the shared library
calling exit.
It seems SASSigSegvHandler function does this (./src/sassim.cpp)
Shouldn't it do a return ?

F.

**Comment by munroesj** [comment]
This is an error case, there is a sigsegv for an address outside of the SASRegion and can not be handled (via SASAttachAllocatedAddr) within the SAS framework.

Disabling this thread's sigsigv handler and returning will result in the re-execution of the offending instruction and another sigsegv. This will likely kill this thread. 

Not sure what state the application is in after this (may be hung waiting for updates by the thread that just died). 

So unless the controlling application has it own (properly nested) sigsegv handler not sure return is good idea.

But I would consider adding a SASJoinRegion API to allow the application to choose the behavior for this case. 

Also I need to think about the storage oldSigSegV which is currently static. 

In a threaded application the second thread will overwrite the applications oldSigSegV and loose track of sigactions established by the controlling application. 

On reflection, as sigaction is a thread local scope under  IEEE Std 1003.1-2001, I think we should make oldSigSegV __thread local.

**Comment by RajalakshmiS** [comment]
Commited Steve's patch to handle this.
However, Warning will still be present which can be ignored.[Incase if SASAttachAllocatedAddr fails and there is no signal handler, exit is called.]

**Comment by tuliom** [comment]
Closing this based on the last comment.
