### ISSUE TITLE
Missing arm support

### ISSUE THREAD

**Issue by frediz** [sphde/sphde#20]
Hi,
sphde doesn't compile on arm64/armhf because of missing function __arch_pause in sasatom_generic.h : 
```
/bin/bash ../libtool  --tag=CXX --silent  --mode=compile g++ -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -D__SASSIM__ -Wall -Wwrite-strings -Woverloaded-virtual -pthread -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -c -o libsphde_la-sphsinglepcqueue.lo `test -f 'sphsinglepcqueue.cpp' || echo './'`sphsinglepcqueue.cpp
sphsinglepcqueue.cpp: In function ‘void* SPHSinglePCQueueAllocStrideDirectSpinPause(SPHSinglePCQueue_t)’:
sphsinglepcqueue.cpp:592:28: error: ‘__arch_pause’ was not declared in this scope
               __arch_pause();
                            ^
sphsinglepcqueue.cpp:602:28: error: ‘__arch_pause’ was not declared in this scope
               __arch_pause();
                            ^
sphsinglepcqueue.cpp: In function ‘void* SPHSinglePCQueueGetNextCompleteDirectSpinPause(SPHSinglePCQueue_t)’:
sphsinglepcqueue.cpp:712:28: error: ‘__arch_pause’ was not declared in this scope
               __arch_pause();
                            ^
sphsinglepcqueue.cpp:722:28: error: ‘__arch_pause’ was not declared in this scope
               __arch_pause();
                            ^
```

Thanks,
F.

**Comment by munroesj** [comment]
Well someone with the platform skills and access to hardware would need to provide and test a sasatom_arm[32|64].h implementation.

We don't have access to ARM hardware.

I suppose we could work on a generic C11 __atomic implementation for platforms we don't currently support.

**Comment by frediz** [comment]
@munroesj , I agree this need some knowledge. For the hardware wouldn't an arm qemu vm be enough ?

Also, I think your idea of a generic C11 _atomic implementation is very good, because the problem is
wider that what I reported, actually. You can see here it also happens on many architectures : 
https://buildd.debian.org/status/package.php?p=sphde

I've pushed sphde into Debian unstable and having compilation ok on most of the supported architecture
would help to get it accepted to next Debian release.
Thanks Steve,
F.

**Comment by RajalakshmiS** [comment]
Fixed
