### ISSUE TITLE
Fix SPHDE_SO_VERSION

### ISSUE THREAD

**Issue by frediz** [sphde/sphde#32]
For 1.2.1 version, the SPHDE_SO_VERSION=1:2:1 is wrong,
as mentioned in
http://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html

"Never try to set the interface numbers so that they correspond to the release number of your package. This is an abuse that only fosters misunderstanding of the purpose of library versions."
On Debian,
debian@vm83:~/sphde-1.2.1$ find ../sphde-1.2.0/ -name 'libsphde.so.*'
../sphde-1.2.0/debian/tmp/usr/lib/powerpc-linux-gnu/libsphde.so.1
../sphde-1.2.0/debian/tmp/usr/lib/powerpc-linux-gnu/libsphde.so.1.0.2
../sphde-1.2.0/debian/libsphde1/usr/lib/powerpc-linux-gnu/libsphde.so.1
../sphde-1.2.0/debian/libsphde1/usr/lib/powerpc-linux-gnu/libsphde.so.1.0.2
../sphde-1.2.0/src/.libs/libsphde.so.1
../sphde-1.2.0/src/.libs/libsphde.so.1.0.2
debian@vm83:~/sphde-1.2.1$ find ../sphde-1.2.1/ -name 'libsphde.so.*'
../sphde-1.2.1/debian/tmp/usr/lib/powerpc-linux-gnu/libsphde.so.0
../sphde-1.2.1/debian/tmp/usr/lib/powerpc-linux-gnu/libsphde.so.0.1.2
../sphde-1.2.1/debian/libsphde1/usr/lib/powerpc-linux-gnu/libsphde.so.0
../sphde-1.2.1/debian/libsphde1/usr/lib/powerpc-linux-gnu/libsphde.so.0.1.2
../sphde-1.2.1/src/.libs/libsphde.so.0
../sphde-1.2.1/src/.libs/libsphde.so.0.1.2
debian@vm83:~/sphde-1.2.1$ objdump -p ../sphde-1.2.0/src/.libs/libsphde.so.1.0.2 | sed -n -e's/^[[:space:]]*SONAME[[:space:]]*//p' | sed -r -e's/([0-9])\.so\./\1-/; s/\.so(\.|$)//; y/_/-/; s/(.*)/\L&/'
libsphde1
debian@vm83:~/sphde-1.2.1$ objdump -p ../sphde-1.2.1/src/.libs/libsphde.so.0.1.2 | sed -n -e's/^[[:space:]]*SONAME[[:space:]]*//p' | sed -r -e's/([0-9])\.so\./\1-/; s/\.so(\.|$)//; y/_/-/; s/(.*)/\L&/'
libsphde0

So by jumping to 1.2.1, there is a change of SONAME, which is not the idea, since I only saw a few symbols added. Only revision needs to be increased I'd say

F.

**Comment by RajalakshmiS** [comment]
@frediz Updated it as 1.3.0 , Can you please check now?

**Comment by RajalakshmiS** [comment]
@frediz Can we close this?
