### ISSUE TITLE
Get rid of the following warnings

### ISSUE THREAD

**Issue by tuliom** [sphde/sphde#34]
I received the following warnings on a RHEL 6:

    warning: ignoring unsupported tag `WARN_AS_ERROR          =' at line 746, file ./doc/libsphde-doxygen-sasutil.doxy
    warning: ignoring unsupported tag `WARN_AS_ERROR          =' at line 746, file ./doc/libsphde-doxygen-sph.doxy

**Comment by RajalakshmiS** [comment]
@tuliom  This depends on the doxygen version installed on the system.

**Comment by tuliom** [comment]
AFAIU, WARN_AS_ERROR is a new tag which isn't available on RHEL6's doxygen.
It's default value is NO, and we're setting it to NO.
Thus, it seems safe to me to remove that definition.

**Comment by RajalakshmiS** [comment]
@tuliom  Ack. Removed the tags that are not used (checked in RHEL 7.2)
I looked for a tag to suppress 'warning: ignoring unsupported tag'. 
I could not find  a method to do that.
