### ISSUE TITLE
Mips64el support patch

### ISSUE THREAD

**Issue by frediz** [sphde/sphde#39]
Hi,
in Debian, Radovan Birdic was kind enough to submit a patch to support mips64el.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844613
Could you have a look at it ?
Would it be possible to extend support to mips and mipsel as well ?
Thanks,

F.

**Comment by RajalakshmiS** [comment]
@frediz 

1) I dont have a machine to test this. Can Radovan help in testing it or Can you share the machine?
2) I need output of
cat /proc/self/maps
command to validate the patch.

**Comment by tuliom** [comment]
3. We need a properly formatted patch with a commit message and his signed-off-by, showing that he agrees with https://github.com/sphde/sphde/blob/master/CONTRIBUTING.md

**Comment by rbirdic** [comment]
Hi,

I'm willing to help.

I am sending you sphde full build log (testing included) built on my local mips64el machine.
If any additional testing is needed I could do it.

@frediz
Are you planing to adapt my patch to latest sphde version or you want me to do that?


Output of "cat /proc/self/maps":

> 120000000-12000e000 r-xp 00000000 08:01 6422552                          /bin/cat
> 12001d000-12001e000 r--p 0000d000 08:01 6422552                          /bin/cat
> 12001e000-12001f000 rw-p 0000e000 08:01 6422552                          /bin/cat
> 12001f000-120040000 rwxp 00000000 00:00 0                                [heap]
> fff6e81000-fff6ea3000 rw-p 00000000 00:00 0 
> fff6ea3000-fff7031000 r--p 00000000 08:01 20842097                       /usr/lib/locale/locale-archive
> fff7031000-fff7033000 rw-p 00000000 00:00 0 
> fff7033000-fff71d3000 r-xp 00000000 08:01 19155007                       /lib/mips64el-linux-gnuabi64/libc-2.22.so
> fff71d3000-fff71e3000 ---p 001a0000 08:01 19155007                       /lib/mips64el-linux-gnuabi64/libc-2.22.so
> fff71e3000-fff71e9000 r--p 001a0000 08:01 19155007                       /lib/mips64el-linux-gnuabi64/libc-2.22.so
> fff71e9000-fff71ed000 rw-p 001a6000 08:01 19155007                       /lib/mips64el-linux-gnuabi64/libc-2.22.so
> fff71ed000-fff71f2000 rw-p 00000000 00:00 0 
> fff71f2000-fff7218000 r-xp 00000000 08:01 19155003                       /lib/mips64el-linux-gnuabi64/ld-2.22.so
> fff7223000-fff7226000 rw-p 00000000 00:00 0 
> fff7226000-fff7227000 r-xp 00000000 00:00 0                              [vdso]
> fff7227000-fff7228000 r--p 00025000 08:01 19155003                       /lib/mips64el-linux-gnuabi64/ld-2.22.so
> fff7228000-fff722a000 rw-p 00026000 08:01 19155003                       /lib/mips64el-linux-gnuabi64/ld-2.22.so
> ffffb00000-ffffb21000 rwxp 00000000 00:00 0                              [stack]

Build log:
[sphde_1.3.0-1_mips64el.txt](https://github.com/sphde/sphde/files/621760/sphde_1.3.0-1_mips64el.txt)

**Comment by frediz** [comment]
@rbirdic if you are willing to port your patch on the new master, I'll let you do that, especially if it's not trivial :) and also this way of doing will better comply with the Developer Certificate of Origin.

@tuliom in the DCO in the CONTRIBUTING.md, there is an additional term that is not in the DCO 1.1 written here : http://developercertificate.org/ . How come ?

On my side, I'll setup a mips64el VM if the sphde team needs

**Comment by RajalakshmiS** [comment]
@frediz I will verify the patch with the logs provided. For now, I dont need machine.

**Comment by frediz** [comment]
@RajalakshmiS ack

**Comment by RajalakshmiS** [comment]
@frediz  @rbirdic  Patch changes look good. As mentioned by tuliom earlier,
" We need a properly formatted patch with a commit message and his signed-off-by, showing that he agrees with https://github.com/sphde/sphde/blob/master/CONTRIBUTING.md"

**Comment by rbirdic** [comment]
I was adapted patch to latest sphde version.
Here is pull request:
https://github.com/sphde/sphde/pull/40

**Comment by RajalakshmiS** [comment]
Merged.
