### ISSUE TITLE
Mips/mipsel support patch

### ISSUE THREAD

**Issue by rbirdic** [sphde/sphde#42]
After added support for mips64el, it would be good to add support for mips32 also.

I defined base address, region and segment size for mips32(little and big endian):

```
#ifdef __mips__
# define     __SAS_BASE_ADDRESS      0x60000000UL    /* 1,5GB */
# define     RegionSize              0x10000000UL    /* 256MB */
# define     SegmentSize             0x01000000UL    /*  16MB */
# define     __SAS_SHMAP_MAX         0x01000000UL    /*  16MB */
#endif
```

With these values package builds successfully on mipsel.

Mipsel "cat /proc/self/maps" output:

> 00400000-0040c000 r-xp 00000000 08:03 7999116                            /bin/cat
> 00418000-0041c000 r--p 00008000 08:03 7999116                            /bin/cat
> 0041c000-00420000 rw-p 0000c000 08:03 7999116                            /bin/cat
> 00420000-00444000 rwxp 00000000 00:00 0                                  [heap]
> 77a94000-77abc000 rw-p 00000000 00:00 0 
> 77abc000-77c28000 r-xp 00000000 08:03 7997546                            /lib/mipsel-linux-gnu/libc-2.24.so
> 77c28000-77c38000 ---p 0016c000 08:03 7997546                            /lib/mipsel-linux-gnu/libc-2.24.so
> 77c38000-77c40000 rw-p 0016c000 08:03 7997546                            /lib/mipsel-linux-gnu/libc-2.24.so
> 77c48000-77c6c000 r-xp 00000000 08:03 7997541                            /lib/mipsel-linux-gnu/ld-2.24.so
> 77c70000-77c78000 rw-p 00000000 00:00 0 
> 77c78000-77c7c000 rw-p 00020000 08:03 7997541                            /lib/mipsel-linux-gnu/ld-2.24.so
> 7fcd8000-7fcfc000 rwxp 00000000 00:00 0                                  [stack]
> 7fff4000-7fff8000 r-xp 00000000 00:00 0                                  [vdso]

I am sending you sphde full build log (testing included) built on my local mipsel machine.

[sphde_1.3.0-1_mipsel.txt](https://github.com/sphde/sphde/files/652089/sphde_1.3.0-1_mipsel.txt)

I was adapted patch to latest sphde version.
Here is pull request:
https://github.com/sphde/sphde/pull/41

**Comment by RajalakshmiS** [comment]
Merged
