### ISSUE TITLE
Test build failure

### ISSUE THREAD

**Issue by frediz** [sphde/sphde#61]
Hi,
on Debian Unstable ppc64el, sphde fails to compile  tests/sassim_t.c (gcc 10 and 11) with the following error : 

```gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Werror -Wwrite-strings -pthread -g -O2 -ffile-prefix-map=/build/sphde-gZV5dj/sphde-1.4.0=. -fstack-protector-strong -Wformat -Werror=format-security -mhtm -c -o tests/sassim_t.o tests/sassim_t.c
In file included from /usr/include/string.h:519,
                 from tests/sassim_t.c:16:
In function ‘memset’,
    inlined from ‘sassim_heap_test2’ at tests/sassim_t.c:404:3,
    inlined from ‘main’ at tests/sassim_t.c:573:15:
/usr/include/powerpc64le-linux-gnu/bits/string_fortified.h:56:10: error: ‘__builtin_memset’ offset [0, 16777215] is out of the bounds [0, 0] [-Werror=array-bounds]
   56 |   return __builtin___memset_chk (__dest, __ch, __len, __bos0 (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~```

Last time it worked, it was with gcc 8.

F.

**Comment by munroesj52** [comment]
Ok I'll take a look, tho sphde source does not use this directly.

Looks this builtin was dropped in GCC9. 

Does this fail on other platforms? Seems like it would.

**Comment by munroesj52** [comment]
Ok this is as case where I am memset'ing a block of shared memory to zero. This is definitely outside of the normal heap or stack, but should be allowed for any memory allocated from via posix shmget or mmap.

might be a compiler bug where it is being over protective. Fortify many?

**Comment by munroesj52** [comment]
A normal GCC 9 build does not trigger this.

So I need to see the full GCC command line.
I assume someone is asserting _FORTIFY_SOURCE=1/2.  which pulls in string_fortified.h. But I have no idea how/where this is happening.

I tried adding -D_FORTIFY_SOURCE=1 to CFLAGS but this just kills the build with bogus:
<command-line>: error: "_FORTIFY_SOURCE" redefined [-Werror]

More information please

**Comment by munroesj52** [comment]
Same results with GCC10 Fedora 33

**Comment by frediz** [comment]
Hi @munroesj52 , sorry, I should have include the command line : 
```gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Werror -Wwrite-strings -pthread -g -O2 -ffile-prefix-map=/build/sphde-bw86QB/sphde-1.4.0=. -fstack-protector-strong -Wformat -Werror=format-security -mhtm -c -o tests/sassim_t.o tests/sassim_t.c```

Debian adds some hardening options by default.
I also confirm this fails on other arches as well.
Also Ubuntu does/fails the same way : 
```gcc -DHAVE_CONFIG_H -I. -I..   -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Werror -Wwrite-strings  -g -O3 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -mhtm -c -o tests/sassim_t.o tests/sassim_t.c```

**Comment by munroesj52** [comment]
I need the configure string
I keep failing on the configure 
../sphde/configure CFLAGS='-Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Werror -Wwrite-strings -pthread -O2 -g0 -march=native' CXXFLAGS='-Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Werror -Wwrite-strings -pthread -O2 -g0 -march=native'

configure: error: *** No static libc found. Try to install glibc-static or libc6-dev.

but 
$ sudo apt install libc6-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libc6-dev is already the newest version (2.31-0ubuntu9.2).

Same on Fedora 33 GCC 10. 

The -Werror seems to force the static pthread check.

**Comment by munroesj52** [comment]
Tried configuring without all then options then manually running the gcc with all the options (except -ffile=) on Ubuntu 20 LTS and Fedora 33 on x86_64 but still can not trigger the error.

Frustrating

**Comment by munroesj52** [comment]
Is the source from git master or tagged 1.4?

**Comment by frediz** [comment]
Thank you Steve for your time.

Ubuntu 20.04 does not have gcc 11 (and gcc-10 seemed to work in Ubuntu).
So, if you want to try on Ubuntu, I could reproduce it with 21.04 and gcc-11/g++-11.
```autoreconf -f -i``` is run before configure.
Configure line is the following from the builder : 
```./configure --build=powerpc64le-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=\${prefix}/lib/powerpc64le-linux-gnu --libexecdir=\${prefix}/lib/powerpc64le-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking```

The source tree is the one from 1.4 tag with patch from commit https://github.com/sphde/sphde/commit/10897accedb5adc6ca54c91e49e482bb853cb59d 
You'll need to ```apt install gcc-11 g++-11``` and export CC=gcc-11 and CXX=g++-11 .
Hope that helps,

Fred

**Comment by munroesj52** [comment]
This is PPC64le? Think it would fail for AMD64/X86_64? 

I try to find a system to install 21.04, X86_64 would be easier.
Thanks.

**Comment by frediz** [comment]
I showed on ppc64el but it also fails on 21.04/amd64 the same way.
Same as above applies to build on amd64 (autoreconf, install of gcc-11 g++-11, 1.4 tag + commit https://github.com/sphde/sphde/commit/10897accedb5adc6ca54c91e49e482bb853cb59d ).
Configure line is then : 
```
./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=\${prefix}/lib/x86_64-linux-gnu --libexecdir=\${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking```

**Comment by munroesj52** [comment]
Ok look at:
https://github.com/munroesj52/sphde/commit/182318a6032e58e7e32e204e1ea3e26a8c989e06

**Comment by munroesj52** [comment]
Ok I reproduced the failure with AT15 and I think I have a work around that at least passes the AT15 compile test.

Can you test with https://github.com/munroesj52/sphde/tree/bug61 branch?
Or do you need a pull request against master?

**Comment by frediz** [comment]
Hi Steve,
I  cherrypicked your patch https://github.com/munroesj52/sphde/commit/182318a6032e58e7e32e204e1ea3e26a8c989e06
on top of the debian source and it fixed the build.
For the time being I can have the patch in the debian/patches directory, but if you can make a pull request
and get it upstream, that'd be nice.
Thanks,
F.

**Comment by munroesj52** [comment]
I think this ready to merge but a quick review would be good.
